[project]
name = "fastapi_oauth20"
version = "0.0.1"
description = "FastAPI easily integrates with clients OAuth 2.0"
authors = [
    { name = "Wu Clan", email = "jianhengwu0407@gmail.com" },
]
dependencies = [
    "httpx>=0.18.0",
    "fastapi>=0.100.0",
]
requires-python = ">=3.8"
readme = "README.md"
license = { text = "MIT" }

[tool.pdm.dev-dependencies]
lint = [
    "ruff>=0.2.0",
    "pre-commit>=3.5.0",
]

[tool.ruff]
line-length = 120
cache-dir = "./.ruff_cache"

[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.lint.isort]
lines-between-types = 1
order-by-type = true

[tool.ruff.format]
quote-style = "single"

[tool.pdm]
package-type = "library"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
